version: "3.1"
services:
  spring:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
