server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ttbkk?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: password
  flyway:
    user: root
    password: password
    schemas: ttbkk
    url: jdbc:mysql://localhost:3306/ttbkk?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

# 테스트 코드 돌릴때 사용 하는 db 설정
# h2 데이터 베이스 사용
#
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/ttbkk
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true

logging:
  config: classpath:logback-local.xml