version: "3.7"
services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: ttbkk-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ttbkk
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./data:/var/lib/mysql